version: '3.8'

services:
  php:
    image: php:8.2-fpm
    volumes:
      - ./server:/var/www/html
    expose:
      - 9000

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./server:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
